language: cpp
compiler:
  - gcc-4.8
  - clang
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
  - if [ "$CXX" = "g++" ]; then
       export CXX="g++-4.8";
    fi
  - $CXX --version
  - make
script:
  - make test

notifications:
  emails:
    - c89-compiler@kmc.gr.jp
  on_success: always
  on_failure: always
  slack:
    secure: NLJP8oba5UYsunziGsiX5qvfTJ7zfL9v5bnuC8LD/rPrlNptI4ZXTz0S6fJYLWkAMzDXaA0xes2ERVHw8W8dPXBdfAyQpQaAaELQCWWENaXAuv2cPCk+NOuY51VWXKdlckS8gLrPori8PndtZrcLrFTT7XI248cWUavjWt784v45Ajt3fXPL3rwaEp4GtyOyO5PtW079LB1RkItUZzBcGTYzulaZgoF9IthW5e2EsU5c7nvDo4kwNQ+Ohag0zIwEJknZhQTODTj9P6FzT0ch6icNLp7vefkTFPCjOyHq1vPw8Cf+FSpE748JlG50pezKUI9I7Ak9Ia2qtAax0dt5h3GQC1Ia9I7TYcjTuES7l9qFqEepEhgkUjTpFa6ApDAV4ubirQuYCSgLa154CT0nbe+07kInt3ER2pflIJQYG1Mh22oOUCif85r+XflLPLIsyX2Z5MRwp14Oj6sxjlM7XcqXrg+9kMjX2JfgA55J1U+PDUjB0AollNaWQm5SMk6yngsYLIN79d3WyEM9iD/VqRXwHmvgGOb75Y/lRtj5ym2BjVCa4arbXgqVU+UliaK48gqEqH6ic0yBJwlAkkCKUSDWWPT8Dd7wfOO3SpoWn8E1TbYl6AY/BM12iyIbottrbp8QPFxWWN4GYG8aHPAFRutuMZMTy0QrJFqGkuika7I=
