#ifndef KMC_C89_COMPILER_USE_VECTOR_H
#define KMC_C89_COMPILER_USE_VECTOR_H

#include "../src/vector.h"

/* VECTORREF(int) */
DECLARE_VECTOR(int)
DECLARE_DEFAULT_METHODS(int)

/* VECTORREF(VECTORREF(int)) */
DECLARE_VECTOR(VECTORREF(int))
DECLARE_DEFAULT_VECTOR_METHODS(int)

#endif  /* KMC_C89_COMPILER_USE_VECTOR_H */
